/**CREACIÓN DE TABLAS Y SECUENCIAS**/

CREATE TABLE CLIENTES (
	ID INTEGER PRIMARY KEY,
	CEDULA INT NOT NULL,
    NOMBRE VARCHAR2(255) NOT NULL,
    TELEFONO INT,
    DIRECCION VARCHAR2(255) NOT NULL
);
CREATE SEQUENCE clientes_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE ESTADO_GUIAS (
	ID INTEGER PRIMARY KEY,
	ESTADO VARCHAR2(255) NOT NULL
);
CREATE SEQUENCE estado_guias_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE RASTREO_GUIAS (
	ID INTEGER PRIMARY KEY,
	ID_ESTADO_GUIA INT,
    FECHA_HORA_ESTADO TIMESTAMP,
    CONSTRAINT FK_ESTADO_GUIAS_RASTREO FOREIGN KEY (ID_ESTADO_GUIA) REFERENCES ESTADO_GUIAS(ID)
);
CREATE SEQUENCE rastreo_guias_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE DEPARTAMENTOS(
	ID INTEGER PRIMARY KEY,
	DEPARTAMENTO VARCHAR2(255) NOT NULL
);
CREATE SEQUENCE departamentos_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE CIUDADES (
	ID INTEGER PRIMARY KEY,
	CIUDAD VARCHAR2(255) NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    CONSTRAINT FK_DEPARTAMENTOS_CIUDADES FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID)
);
CREATE SEQUENCE ciudades_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE CODIGOS_POSTALES (
	ID INTEGER PRIMARY KEY,
    ID_CIUDAD INT NOT NULL,
	CODIGO_POSTAL INT NOT NULL,
    CONSTRAINT FK_CIUDADES_CODIGOS_POSTALES FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES(ID)
);
CREATE SEQUENCE codigos_postales_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE EMPLEADOS (
	ID INTEGER PRIMARY KEY,
	NOMBRE VARCHAR2(255) NOT NULL,
    CEDULA INT NOT NULL,
    CODIGO_EMPLEADO INT,
	DIRECCION VARCHAR2(255),
    TELEFONO INT,
    SALARIO INT,
	ID_EMPLEADO_JEFE INT,
    CARGO VARCHAR2(255),
    CONSTRAINT FK_EMPLEADO_JEFE_EMPLEADOS FOREIGN KEY (ID_EMPLEADO_JEFE) REFERENCES EMPLEADOS(ID)
);
CREATE SEQUENCE empleados_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE CENTRO_RECIBOS (
	ID INTEGER PRIMARY KEY,
	ID_CIUDAD INT NOT NULL,
	NOMBRE VARCHAR2(255) NOT NULL,
    DIRECCION VARCHAR2(255),
    TELEFONO INT,
	TIPO_CENTRO_RECIBO VARCHAR2(255) NOT NULL,
    CONSTRAINT FK_CIUDADES_CENTRO_RECIBOS FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES(ID)    
);
CREATE SEQUENCE centro_recibos_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

ALTER TABLE CENTRO_RECIBOS
ADD CONSTRAINT CHECK_TIPO_CENTRO_RECIBO
  CHECK (TIPO_CENTRO_RECIBO IN ('CONVENCIONAL','TERMINAL DE CARGA'));


CREATE TABLE CENTRO_RECIBOS_EMPLEADOS (
ID INTEGER PRIMARY KEY, 
ID_EMPLEADO INT,
ID_CENTRO_RECIBO INT ,
CONSTRAINT FK_EMPLEADOS_CENTRO_RECIBOS FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID),
CONSTRAINT FK_CENTRO_RECIBOS_EMPLEADOS FOREIGN KEY (ID_CENTRO_RECIBO) REFERENCES CENTRO_RECIBOS (ID)
);
CREATE SEQUENCE centro_recibos_empleados_seq START WITH 1 INCREMENT BY 1 NOCYCLE;


CREATE TABLE VEHICULOS (
	ID INTEGER PRIMARY KEY,
	MARCA VARCHAR2(255),
    MODELO INT,
    LINEA VARCHAR2(255),
	TIPO_COMBUSTIBLE VARCHAR2(255) NOT NULL,
    KILOMETRAJE INT,
    CAPACIDAD VARCHAR2(255) NOT NULL,
    ID_CENTRO_RECIBO INT,
    CONSTRAINT FK_CENTRO_RECIBOS_VEHICULOS FOREIGN KEY (ID_CENTRO_RECIBO) REFERENCES CENTRO_RECIBOS(ID)
);
CREATE SEQUENCE vehiculos_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

ALTER TABLE VEHICULOS
ADD CONSTRAINT CHECK_TIPO_COMBUSTIBLE
  CHECK (TIPO_COMBUSTIBLE IN ('DIESEL','GASOLINA'));

ALTER TABLE VEHICULOS
ADD CONSTRAINT CHECK_CAPACIDAD
  CHECK (CAPACIDAD IN ('2.5 TON','2.8 TON','3.3 TON','3.5 TON','5 TON','6 TON','11 TON','700 KG'));

CREATE TABLE REVISIONES (
	ID INTEGER PRIMARY KEY,
	KILOMETRAJE_REVISION INT NOT NULL
);
CREATE SEQUENCE revisiones_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE OPERACIONES_REVISIONES (
	ID INTEGER PRIMARY KEY,
	OPERACION VARCHAR2(255),
    ID_REVISION INT NOT NULL,
    CONSTRAINT FK_REVISIONES_OPERACIONES_REVISIONES FOREIGN KEY (ID_REVISION) REFERENCES REVISIONES(ID)
);
CREATE SEQUENCE operaciones_revisiones_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE MANTENIMIENTOS (
	ID INTEGER PRIMARY KEY,
	FECHA_MANTENIMIENTO DATE,
    HORA_ENTRADA TIMESTAMP,
    HORA_SALIDA TIMESTAMP,
    ID_EMPLEADO INT,    
    ESTADO VARCHAR2(255) default 'NO REALIZADO' NOT NULL,
    OBSERVACIONES VARCHAR2(255),
    ID_VEHICULO INT,
    ID_REVISION INT,
    CONSTRAINT FK_EMPLEADOS_MANTENIMIENTOS FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID),
    CONSTRAINT FK_VEHICULOS_MANTENIMIENTOS FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS(ID),
    CONSTRAINT FK_REVISION_MANTENIMIENTOS FOREIGN KEY (ID_REVISION) REFERENCES REVISIONES(ID)
);
CREATE SEQUENCE mantenimientos_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

ALTER TABLE MANTENIMIENTOS
ADD CONSTRAINT CHECK_ESTADO_MANTENIMIENTO
  CHECK (ESTADO IN ('REALIZADO','NO REALIZADO'));

CREATE TABLE ENVIO_MERCANCIA (
	ID INTEGER PRIMARY KEY,
    NUMERO_GUIA INT NOT NULL,
    PESO_REAL INT,
    ANCHO FLOAT,    
    ALTO FLOAT,
    LARGO FLOAT,
    PESO_VOLUMEN FLOAT,    
    TIPO_SERVICIO VARCHAR(255) NOT NULL,
    FECHA_HORA_DESPACHO TIMESTAMP,  
    ID_CLIENTE_REMITE INT,    
    ID_CLIENTE_DESTINO INT,
    FECHA_HORA_ENTREGA TIMESTAMP,  
    OBSERVACIONES VARCHAR2(255),    
    ID_CIUDAD_ORIGEN INT,
    ID_CIUDAD_DESTINO INT,
    ID_CODIGO_POSTAL_ORIGEN INT,    
    ID_CODIGO_POSTAL_DESTINO INT,
    UNIDADES INT,
    FLETE_FIJO FLOAT,   
    FLETE_VARIABLE FLOAT,
    OTROS_VALORES FLOAT,
    VALOR_SERVICIO INT,   
    ID_ESTADO INT,
    CONSTRAINT FK_CLIENTES_REMITE_ENVIO_MERCANCIA FOREIGN KEY (ID_CLIENTE_REMITE) REFERENCES CLIENTES (ID),
    CONSTRAINT FK_CLIENTES_DESTINO_ENVIO_MERCANCIA FOREIGN KEY (ID_CLIENTE_DESTINO) REFERENCES CLIENTES (ID),
    CONSTRAINT FK_CIUDADES_ORIGEN_ENVIO_MERCANCIA FOREIGN KEY (ID_CIUDAD_ORIGEN) REFERENCES CIUDADES(ID),
    CONSTRAINT FK_CIUDADES_DESTINO_ENVIO_MERCANCIA FOREIGN KEY (ID_CIUDAD_DESTINO) REFERENCES CIUDADES(ID),
    CONSTRAINT FK_POSTAL_ORIGEN_ENVIO_MERCANCIA FOREIGN KEY (ID_CODIGO_POSTAL_ORIGEN) REFERENCES CODIGOS_POSTALES (ID),
    CONSTRAINT FK_POSTAL_DESTINO_ENVIO_MERCANCIA FOREIGN KEY (ID_CODIGO_POSTAL_DESTINO) REFERENCES CODIGOS_POSTALES (ID),
    CONSTRAINT FK_ESTADO_GUIAS_ENVIO_MERCANCIA FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_GUIAS (ID)
);
CREATE SEQUENCE envio_mercancia_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
   
ALTER TABLE ENVIO_MERCANCIA
ADD CONSTRAINT CHECK_TIPO_SERVICIO
  CHECK (TIPO_SERVICIO IN ('CARGA AEREA','MERCANCIA','MENSAJERIA','FIRMA DE DOCUMENTOS','RADICACION DE DOCUMENTOS'));

